export default {
    SET_USER: "SET_USER",
    SET_USER_TYPE: "SET_USER_TYPE",
    SET_USER_PHONE: "SET_USER_PHONE",
    SET_ACCOUNT: "SET_ACCOUNT",
    SET_DEVICE_TOKEN: "SET_DEVICE_TOKEN",
    SET_USER_DATA: "SET_USER_DATA",
    SET_CATEGORY: 'SET_CATEGORY',
    SELECT_CATEGORY: "SELECT_CATEGORY",
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_TICKET_PHOTO: 'SET_TICKET_PHOTO',
    TICKET_PAYMENT: 'TICKET_PAYMENT',
    SET_TICKETS: 'SET_TICKETS',
    SET_CHATLIST: 'SET_CHATLIST',
    SET_CURRENT_TICKET: 'SET_CURRENT_TICKET',
    SET_VOIP_TOKEN: "SET_VOIP_TOKEN",
    SET_SESSION: 'SET_SESSION',


}